-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity tvmgen_default_run_tvmgen_default_fused_nn_contrib_conv2d_NCHWc_add_nn_relu_1_1_Pipeline_VITIS_LeOg is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of tvmgen_default_run_tvmgen_default_fused_nn_contrib_conv2d_NCHWc_add_nn_relu_1_1_Pipeline_VITIS_LeOg is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101010000111001000010010", 1 => "10111101110111101111011010011000", 2 => "10111110000100000110110010101111", 3 => "10111110010100011100100100111001", 
    4 => "10111110001101110110111101010110", 5 => "10111110010111001001101111100001", 6 => "10111110000010010000010000110010", 7 => "10111110010010000110110000000101", 
    8 => "10111110100010010101100000100110", 9 => "10111110100001000011010001100100", 10 => "10111101100110111111011110110110", 11 => "00111100010110011010010110111111", 
    12 => "10111011100100011010010001100001", 13 => "10111110110101000101100011101001", 14 => "10111110001101110001010100000111", 15 => "10111101000111100101010110100011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

